name: run python script
on:
  push:
    branches: [shyam]

env:
  USERNAME: ${{secrets.USERNAME}}
  PASSWORD: ${{secrets.PASSWORD}}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: install dependencies
        run: |
          pip install -r requirements.txt
      - name: run streamlit
        run:
          streamlit run main.py ${{secrets.USERNAME}} ${{secrets.PASSWORD}}
